//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectowebB.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_details
    {
        public int id_invoice_detail { get; set; }
        public int id_product { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public int id_invoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
